spring:
  devtools:
    livereload:
      enabled: true
  data:
    web:
      pageable:
        max-page-size: 200
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/lego?characterEncoding=utf8
    username: root
    driver-class-name: com.mysql.jdbc.Driver
#    type: org.springframework.jdbc.datasource.SimpleDriverDataSource
#    schema: classpath:schema.sql
#    password: ''
#    generate-unique-name: true
#    initialization-mode: embedded
logging:
  level:
    org.springframework.web: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    com.github.gxboard.spring-data-jdbc-mybatis: TRACE
    com.github.gxboard.spring-data: TRACE
mybatis:
  config-location: classpath:mybatis-config.xml

